name:
  rotatable_examples

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  rotatable:
    path: ../

flutter:
  uses-material-design: true
